const defaultStructure = {
  type: 1,
  elements: [
    {
      enabled: false,
      el: 'arrow1',
      x: 1,
      y: 2,
    },
    {
      enabled: false,
      el: 'arrow2',
      x: 27,
      y: 2,
    },
    {
      enabled: false,
      el: 'wall1',
      x: 2,
      y: 1,
    },
    {
      enabled: false,
      el: 'wall2',
      x: 2,
      y: 3,
    },
    {
      enabled: false,
      el: 'wall3',
      x: 2,
      y: 5,
    },
    {
      enabled: false,
      el: 'wall4',
      x: 2,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall5',
      x: 2,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall6',
      x: 26,
      y: 1,
    },
    {
      enabled: false,
      el: 'wall7',
      x: 26,
      y: 3,
    },
    {
      enabled: false,
      el: 'wall8',
      x: 26,
      y: 5,
    },
    {
      enabled: false,
      el: 'wall9',
      x: 26,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall10',
      x: 26,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall11',
      x: 2,
      y: 7,
    },
    {
      enabled: false,
      el: 'wall12',
      x: 26,
      y: 7,
    },
    // клапан 1 приточный
    {
      enabled: false,
      el: 'pvlv1',
      x: 2,
      y: 2,
    },
    {
      enabled: false, // клапан 1 приточный
      el: 'pvlv1',
      x: 2,
      y: 2,
    },
    {
      enabled: true, // секция смешения потоков
      manual: false,
      enable: true,
      el: 'air1_up_border',
      bottom: 'air1',
      x: 3,
      y: 2,
    },
    {
      enabled: true, // камера смешения (клапан)
      el: 'mix_inflow',
      manual: true,
      enable: true,
      enableElements: ['air1_up_border', 'arrow5'],
      x: 3,
      y: 3,
    },
    {
      enabled: true, // стрелка направления потока смешения
      manual: false,
      enable: true,
      el: 'arrow5',
      x: 3,
      y: 4,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'pf1',
      bottom: 'air2',
      disableElements: ['pf2', 'pf3'],
      x: 4,
      y: 2,
    },
    {
      enabled: true,
      el: 'pf2',
      manual: true,
      enable: true,
      bottom: 'air3',
      disableElements: ['pf3'],
      x: 5,
      y: 2,
    },
    {
      enabled: true,
      el: 'pf3',
      manual: true,
      enable: true,
      bottom: 'air4',
      x: 6,
      y: 2,
    },
    {
      el: 'air5', // резерв
      x: 7,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh1',
      bottom: 'air6',
      x: 8,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh2',
      bottom: 'air7',
      x: 9,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh3',
      bottom: 'air8',
      x: 10,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toc1',
      bottom: 'air9',
      x: 11,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toc2',
      bottom: 'air10',
      x: 12,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'hum',
      bottom: 'air11',
      x: 13,
      y: 2,
    },
    {
      el: 'air12', // резерв
      x: 14,
      y: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: true,
      el: 'fnresinp',
      bottom: 'air13',
      x: 15,
      y: 2,
      w: 1,
      h: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: false,
      el: 'vpv1',
      bottom: 'air14',
      x: 16,
      y: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: false,
      el: 'vpv1r',
      x: 16,
      y: 3,
    },
    {
      enabled: false, // осн. вентилятор притока не отключается
      el: 'pv1',
      x: 17,
      y: 2,
    },
    {
      enabled: true, // рез. вентилятор притока отключаемый
      enable: true,
      manual: true,
      el: 'pv1r',
      enableElements: ['vpv1r', 'vpv1', 'fnresoutp', 'fnresinp'],
      x: 17,
      y: 3,
    },
    {
      enabled: true, // доп. вентилятор притока отключаемый
      enable: false,
      manual: true,
      el: 'pv2',
      enableElements: ['air15', 'fnresoutp', 'fnresinp'],
      x: 17,
      y: 3,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air15', // резерв
      x: 16,
      y: 3,
    },
    {
      enabled: true,
      enable: true,
      manual: false,
      bottom: 'air16',
      el: 'fnresoutp',
      x: 18,
      y: 2,
      w: 1,
      h: 2,
    },
    {
      el: 'air17', // резерв
      x: 19,
      y: 2,
    },
    {
      el: 'air18', // резерв
      x: 20,
      y: 2,
    },
    {
      enabled: true,
      manual: true,
      enable: true,
      el: 'tnar',
      x: 1,
      y: 3,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'hummes',
      bottom: 'air19',
      x: 21,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      bottom: 'air20',
      el: 'co2',
      x: 22,
      y: 2,
    },
    {
      el: 'air21', // резерв
      x: 23,
      y: 2,
    },
    {
      enabled: true, // датчик давления в канале притока
      enable: true,
      manual: true,
      el: 'press',
      bottom: 'air22',
      x: 24,
      y: 2,
    },
    {
      enabled: true, // датчик температуры в канале притока
      enable: true,
      manual: true,
      el: 'tkan',
      bottom: 'air23',
      x: 25,
      y: 2,
    },
    {
      enabled: true, // жалюзи 2 в канале притока
      enable: true,
      el: 'pvlv2',
      manual: true,
      bottom: 'air24',
      x: 26,
      y: 2,
    },
    {
      enabled: true, // датчик температуры в помещении в канале притока
      enable: true,
      manual: true,
      el: 'troom',
      x: 27,
      y: 3,
    },
  ],
};
const inflowOutflowStructure = {
  type: 1,
  elements: [
    {
      enabled: false,
      el: 'arrow1',
      x: 1,
      y: 2,
    },
    {
      enabled: false,
      el: 'arrow2',
      x: 27,
      y: 2,
    },
    {
      enabled: false,
      el: 'arrow3',
      x: 27,
      y: 5,
    },
    {
      enabled: false,
      el: 'arrow4',
      x: 1,
      y: 5,
    },
    {
      enabled: false,
      el: 'wall1',
      x: 2,
      y: 1,
    },
    {
      enabled: false,
      el: 'wall2',
      x: 2,
      y: 3,
    },
    {
      enabled: false,
      el: 'wall4',
      x: 2,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall5',
      x: 2,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall6',
      x: 26,
      y: 1,
    },
    {
      enabled: false,
      el: 'wall7',
      x: 26,
      y: 3,
    },
    {
      enabled: false,
      el: 'wall9',
      x: 26,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall10',
      x: 26,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall11',
      x: 2,
      y: 7,
    },
    {
      enabled: false,
      el: 'wall12',
      x: 26,
      y: 7,
    },
    // клапан 1 приточный
    {
      enabled: false,
      el: 'pvlv1',
      x: 2,
      y: 2,
    },
    // клапан 1 приточный
    {
      enabled: false,
      el: 'pvlv1',
      x: 2,
      y: 2,
    },
    {
      enabled: true,
      el: 'mix_inflow',
      manual: true,
      enable: true,
      enableElements: ['air45', 'air44', 'air43'],
      x: 3,
      y: 3,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'pf1',
      bottom: 'air1',
      disableElements: ['pf2', 'pf2'],
      x: 4,
      y: 2,
    },
    {
      enabled: true,
      el: 'pf2',
      manual: true,
      enable: true,
      bottom: 'air2',
      disableElements: ['pf3'],
      x: 5,
      y: 2,
    },
    {
      enabled: true,
      el: 'pf3',
      manual: true,
      enable: true,
      bottom: 'air3',
      x: 6,
      y: 2,
    },
    {
      el: 'air4', // резерв
      x: 7,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh1',
      bottom: 'air5',
      x: 8,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh2',
      bottom: 'air6',
      x: 9,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toh3',
      bottom: 'air7',
      x: 10,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toc1',
      bottom: 'air8',
      x: 11,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'toc2',
      bottom: 'air9',
      x: 12,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'hum',
      bottom: 'air10',
      x: 13,
      y: 2,
    },
    {
      el: 'air11', // резерв
      x: 14,
      y: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: true,
      el: 'fnresinp',
      bottom: 'air12',
      x: 15,
      y: 2,
      w: 1,
      h: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: true,
      el: 'vpv1',
      bottom: 'air13',
      x: 16,
      y: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: true,
      el: 'vpv1r',
      bottom: 'air14',
      x: 16,
      y: 3,
    },
    {
      enabled: false, // осн. вентилятор притока не отключается
      el: 'pv1',
      x: 17,
      y: 2,
    },
    {
      enabled: true, // рез. вентилятор притока отключаемый
      enable: true,
      manual: true,
      el: 'pv1r',
      enableElements: ['vpv1r', 'vpv1', 'fnresoutp', 'fnresinp'],
      x: 17,
      y: 3,
    },
    {
      enabled: true, // доп. вентилятор притока отключаемый
      enable: false,
      manual: true,
      el: 'pv2',
      enableElements: ['air15', 'fnresoutp', 'fnresinp'],
      x: 17,
      y: 3,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air15', // резерв
      x: 16,
      y: 3,
    },
    {
      enabled: true,
      enable: true,
      manual: false,
      bottom: 'air16',
      el: 'fnresoutp',
      x: 18,
      y: 2,
      w: 1,
      h: 2,
    },
    {
      el: 'air17', // резерв
      x: 19,
      y: 2,
    },
    {
      el: 'air18', // резерв
      x: 20,
      y: 2,
    },
    {
      enabled: true,
      manual: true,
      enable: true,
      el: 'tnar',
      x: 1,
      y: 3,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      el: 'hummes',
      bottom: 'air19',
      x: 21,
      y: 2,
    },
    {
      enabled: true,
      enable: true,
      manual: true,
      bottom: 'air17',
      el: 'co2',
      x: 22,
      y: 2,
    },
    {
      el: 'air23', // резерв
      x: 23,
      y: 2,
    },
    {
      enabled: true, // датчик давления в канале притока
      enable: true,
      manual: true,
      el: 'press',
      bottom: 'air18',
      x: 24,
      y: 2,
    },
    {
      enabled: true, // датчик температуры в канале притока
      enable: true,
      manual: true,
      el: 'tkan',
      bottom: 'air19',
      x: 25,
      y: 2,
    },
    {
      enabled: true, // жалюзи 2 в канале притока
      enable: true,
      el: 'pvlv2',
      manual: true,
      bottom: 'air17',
      x: 26,
      y: 2,
    },
    {
      enabled: true, // датчик температуры в помещении в канале притока
      enable: true,
      manual: true,
      el: 'troom',
      x: 27,
      y: 3,
    },
  ],
};
export { defaultStructure, inflowOutflowStructure };
