const options = {
  labelVoltage: 'Напряжение, В',
  labelVoltageUnit: 'Напряжение привода, В',
  valuesBoxMaterial: [
    {
      id: 0,
      label: 'Пластик',
    },
    {
      id: 1,
      label: 'Металл',
    },
    {
      id: 2,
      label: 'Без корпуса (монтажная панель)',
    },
  ],
  valuesVoltage: [
    {
      id: 0,
      label: '3x380',
      value: 380,
    },
    {
      id: 1,
      label: '1x220',
      value: 220,
    },
  ],
  labelPower: 'Ном. мощность, кВт',
  valuesTypesFans: [
    {
      id: 0,
      label: 'Асинхронный',
    },
    {
      id: 1,
      label: 'ЕС - мотор',
    },
  ],
  labelTypeRecuperator: 'Тип рекуператора',
  valuesTypesRecuperator: [
    {
      id: 0,
      label: 'Пластинчатый',
    },
    {
      id: 1,
      label: 'Роторный',
    },
  ],
  labelValve: 'Тип привода',
  valuesVoltageValve: [
    {
      id: 0,
      label: '220',
    },
    {
      id: 1,
      label: '24',
    },
  ],
  valuesValveTypePower: [
    {
      id: 0,
      label: 'AC',
    },
    {
      id: 1,
      label: 'AC/DC',
    },
  ],
  valuesTypeValve: [
    {
      id: 0,
      label: 'С возвратной пружиной',
    },
    {
      id: 1,
      label: 'Реверсивный',
    },
    {
      id: 2,
      label: 'С аналоговым управлением',
      icon: 'valve_analog.svg',
    },
  ],
  valuesTypeManual: [
    {
      id: 0,
      label: 'Дискретный (Вкл/Выкл)',
    },
    {
      id: 1,
      label: 'Аналоговый (0-10В)',
    },
  ],
  labelType: 'Тип',
  valuesTypeHeat: [
    {
      id: 0,
      label: 'Водяной',
    },
    {
      id: 1,
      label: 'Электрический',
      icon: 'heater_electric.svg',
    },
  ],
  valuesHeatPurpose: [
    {
      id: 0,
      label: 'Дополнительная мощность к 1',
    },
    {
      id: 1,
      label: 'Доводчик в помещение',
    },
    {
      id: 2,
      label: 'Преднагрев',
    },
  ],
  labelHeatPurpose: 'Назначение',
  labelPowerElectricStage1: 'Мощность 1 ступени, кВт',
  labelPowerElectricStage2: 'Мощность 2 ступени, кВт',
  labelPowerElectricStage3: 'Мощность 3 ступени, кВт',
  labelPowerElectricStage4: 'Мощность 4 ступени, кВт',
  labelPowerElectricStage5: 'Мощность 5 ступени, кВт',
  power220Heater: [
    {
      id: 0,
      label: '0,5',
      stages: [0.5],
    },
    {
      id: 1,
      label: '1,5',
      stages: [1.5],
    },
    {
      id: 2,
      label: '2',
      stages: [2],
    },
    {
      id: 3,
      label: '2,5',
      stages: [2.5],
    },
    {
      id: 4,
      label: '3',
      stages: [3],
    },
  ],
  power380Heater: [
    {
      id: 0,
      label: '4,5',
      stages: [4.5],
    },
    {
      id: 1,
      label: '6',
      stages: [6],
    },
    {
      id: 2,
      label: '7,5',
      stages: [7.5],
    },
    {
      id: 3,
      label: '9',
      stages: [9],
    },
    {
      id: 4,
      label: '12',
      stages: [6, 6],
    },
    {
      id: 5,
      label: '15',
      stages: [7.5, 7.5],
    },
    {
      id: 6,
      label: '18',
      stages: [12, 6],
    },
    // ещё должно быть 9 + 9 мощность
    {
      id: 7,
      label: '22,5',
      stages: [15, 7.5],
    },
    {
      id: 8,
      label: '24',
      stages: [12, 12],
    },
    {
      id: 9,
      label: '27',
      stages: [27],
    },
    {
      id: 10,
      label: '30',
      stages: [15, 15],
    },
    {
      id: 11,
      label: '37,5',
      stages: [15, 15, 7.5],
    },
    {
      id: 12,
      label: '60',
      stages: [15, 15, 15, 15],
    },
    {
      id: 13,
      label: '67,5',
      stages: [15, 15, 15, 15, 7.5],
    },
    {
      id: 14,
      label: '75',
      stages: [15, 15, 15, 15, 15],
    },
    {
      id: 15,
      label: '90',
      stages: [30, 15, 15, 15, 15],
    },
    {
      id: 16,
      label: '120',
      stages: [30, 30, 30, 15, 15],
    },
    {
      id: 17,
      label: '45',
      stages: [15, 15, 15],
    },
  ],
  labelHumidifier: 'Тип увлажнителя',
  valuesHumidifierType: [
    {
      id: 0,
      label: 'Сотовый',
    },
    {
      id: 1,
      label: 'Паровой',
    },
  ],
  rulesPowerStages: {
    min: 0.5,
    max: 120,
    errorMessage: 'Введите корректные данные от 0.5 кВт до 120 кВт',
  },
  rulesPowerFans: {
    min: 0.15,
    max: 30,
    errorMessage: 'Введите корректные данные от 0.15 кВт до 30 кВт',
  },
  rulesCountValveUnits: {
    min: 1,
    max: 2,
    errorMessage: 'Введите корректные данные от 1 до 2',
  },
  rulesCount: {
    min: 1,
    max: 999,
    errorMessage: 'Введите корректные данные от 1 или 999',
  },
  rulesPowerBf: {
    min: 0.075,
    max: 1.8,
    errorMessage: 'Введите корректные данные от 0.075 кВт до 1.8 кВт',
  },
  rulesPowerPump: {
    min: 0.180,
    max: 1,
    errorMessage: 'Введите корректные данные от 0.180 кВт до 1 кВт',
  },
  rulesCurrent: {
    min: 0.01,
    max: 150,
    errorMessage: 'Введите корректные данные от 0.01 А до 150 А',
  },
  rulesCurrentRotor: {
    min: 0.1,
    max: 10,
    errorMessage: 'Введите корректные данные от 0.1 А до 10 А',
  },
  valuesTypeCool: [
    {
      id: 0,
      label: 'Фреоновый',
    },
    {
      id: 1,
      label: 'Водяной',
    },
  ],
  rulesCountCounturCoolFreon: {
    min: 1,
    max: 5,
    errorMessage: 'Введите корректные данные от 1 до 5',
  },
  labelCountCounturCoolFreon: 'Количество контуров',
};
const par_postrecuperator = {
  y: 5,
};
const coord = {
  bf_x: 7,
  bf_y: 2,
  toh1_x: 12,
  toh1_y: par_postrecuperator.y,
  toh2_x: 13,
  toh2_y: par_postrecuperator.y,
  toc1_x: 15,
  toc1_y: par_postrecuperator.y,
  toc2_x: 16,
  toc2_y: par_postrecuperator.y,
  hum_x: 17,
  hum_y: par_postrecuperator.y,
  fnresinp_x: 18,
  fnresinp_y: par_postrecuperator.y,
  vpv1_x: 19,
  vpv1_y: par_postrecuperator.y,
  pv1_x: 20,
  pv1_y: par_postrecuperator.y,
  vpv1r_x: 19,
  vpv1r_y: par_postrecuperator.y + 1,
  pv1r_x: 20,
  pv1r_y: par_postrecuperator.y + 1,
  pv2_x: 20,
  pv2_y: par_postrecuperator.y + 1,
  vv1_x: 5,
  vv1_y: 5,
  fnresoutp_x: 21,
  fnresoutp_y: par_postrecuperator.y,
  hummes_x: 22,
  hummes_y: par_postrecuperator.y,
  co2_x: 23,
  co2_y: par_postrecuperator.y,
  press_x: 24,
  press_y: par_postrecuperator.y,
  tkan_x: 28,
  tkan_y: par_postrecuperator.y,
  pvlv2_y: par_postrecuperator.y,
};

const wallCoord = {
  wallLeft_x: 2,
  wallRight_x: 29,
};
// enableManual - контроль включения отключения дилегирован
const defaultStructure = {
  rs485: true,
  pu: 0,
  box_material: 0,
  manual: 0,
  lum: false,
  clima: false,
  modbus: false,
  co: false,
  cav: false,
  vav: false,
  troom: false,
  version: '0.14.10',
  elements: [
    {
      enabled: false,
      bottom: '',
      el: 'arrow1',
      svg: 'arrow',
      x: 1,
      y: 2,
    },
    {
      enabled: false,
      el: 'arrow2',
      bottom: '',
      svg: 'arrow',
      x: 30,
      y: par_postrecuperator.y,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'arrow3',
      bottom: '',
      svg: 'arrow',
      x: 30,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'arrow4',
      bottom: '',
      svg: 'arrow',
      x: 1,
      y: 5,
    },
    {
      enabled: false,
      el: 'wall1',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 1,
    },
    {
      enabled: false,
      el: 'wall2',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 3,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'vvlv1',
      bottom: 'wall3',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 5,
    },
    {
      enabled: false,
      el: 'wall4',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall5',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall6',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 1,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'air48',
      bottom: 'wall7',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 2,
    },
    {
      enabled: false,
      el: 'wall8',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 3,
    },
    {
      enabled: false,
      el: 'wall9',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 4,
    },
    {
      enabled: false,
      el: 'wall10',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 6,
    },
    {
      enabled: false,
      el: 'wall11',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallLeft_x,
      y: 7,
    },
    {
      enabled: false,
      el: 'wall12',
      bottom: '',
      svg: 'wall',
      x: wallCoord.wallRight_x,
      y: 7,
    },
    // клапан 1 приточный НЕ ОТКЛЮЧАЕМЫЙ
    {
      enabled: false,
      el: 'pvlv1',
      mark: 'КВ1',
      svg: 'valve',
      orders: ['count', 'typeValve_pvlv1', 'voltageValve_pvlv1', 'typePower_pvlv1', 'heat_valve_pvlv1', 'power_heat_valve', 'heat_perimeter_valve_pvlv1',
        'heat_unit_pvlv1'],
      references: [
        {
          name: 'typeValve_pvlv1',
          label: options.labelValve,
          valueId: 0,
          values: options.valuesTypeValve,
          enable: true,
        },
        {
          name: 'voltageValve_pvlv1',
          label: options.labelVoltageUnit,
          valueId: 0,
          values: options.valuesVoltageValve,
          enable: true,
        },
        {
          name: 'typePower_pvlv1',
          label: 'Род тока',
          valueId: 0,
          values: options.valuesValveTypePower,
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'count',
          label: 'Количество приводов, шт',
          value: 1,
          type: 'number',
          rules: options.rulesCountValveUnits,
          enable: true,
        },
        {
          name: 'power_heat_valve',
          label: 'Мощность, кВт',
          value: 6,
          type: 'number',
          rules: options.rulesPowerFans,
          enable: true,
        },
      ],
      switches: [
        {
          name: 'heat_valve_pvlv1',
          label: 'Предварительный подогрев',
          value: false,
          enable: true,
        },
        {
          name: 'heat_perimeter_valve_pvlv1',
          label: 'Периметральный подогрев',
          value: false,
          enable: true,
        },
        {
          name: 'heat_unit_pvlv1',
          label: 'Греющий кабель на привод',
          value: false,
          enable: true,
        },
      ],
      x: 2,
      y: 2,
    },
    {
      enabled: true, // секция смешения потоков
      manual: false,
      enable: false,
      el: 'air1_up_border',
      bottom: 'air1',
      x: 3,
      y: 2,
    },
    {
      enabled: true, // камера смешения (клапан)
      el: 'mix_inflow',
      svg: 'valve',
      mark: 'КР',
      manual: true,
      enable: false,
      enableElements: ['air1_up_border', 'arrow5'],
      orders: ['count'],

      inputs: [
        {
          name: 'count',
          label: 'Количество приводов, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCountValveUnits,
        },
      ],
      x: 3,
      y: 3,
    },
    {
      enabled: true, // стрелка направления потока смешения
      manual: false,
      enable: false,
      el: 'arrow5',
      x: 3,
      y: 4,
    },
    // фильтр притока
    {
      enabled: false,
      enable: true,
      manual: false,
      el: 'pf1',
      mark: 'ФП1',
      svg: 'filter',
      enableManual: true,
      bottom: 'air2',
      orders: ['count'],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      x: 4,
      y: 2,
    },
    // взамен фильтра 2
    {
      enabled: false,
      enable: false,
      manual: false,
      el: 'air3',
      x: 5,
      y: 2,
    },
    // взамен фильтра 3
    {
      enabled: false,
      enable: false,
      manual: false,
      el: 'air4',
      x: 6,
      y: 2,
    },
    // бактерицидный фильтр
    {
      enabled: true,
      el: 'pbf',
      manual: true,
      enable: false,
      mark: 'БФ1',
      bottom: 'air5',
      svg: 'bfilter',
      orders: ['power_bf'],
      inputs: [
        {
          name: 'power_bf',
          label: 'Мощность, кВт',
          value: 0.3,
          type: 'number',
          enable: true,
          rules: options.rulesPowerBf,
        },
      ],
      x: coord.bf_x,
      y: coord.bf_y,
    },
    // нагреватель 1
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'toh1',
      mark: 'Н1',
      svg: 'toh',
      enableElements: ['tkan'],
      bottom: 'air6',
      orders: ['count', 'voltage_toh1', 'type_toh1'],
      references: [
        {
          name: 'voltage_toh1',
          label: options.labelVoltage,
          valueId: 1,
          values: options.valuesVoltage,
          enable: true,
        },
        {
          name: 'type_toh1',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypeHeat,
          referencesValueId: [
            {
              valueId: 0,
              switches: [
                {
                  name: 'pressure_toh1',
                  label: 'Реле перепада давления насоса',
                  value: true,
                  enable: true,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'power_220_toh1',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power220Heater,
                },
                {
                  name: 'power_380_toh1',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power380Heater,
                },
                {
                  name: 'count_stage_toh1',
                  label: 'Количество ступеней',
                  valueId: 0,
                  enable: true,
                  disable: true,
                  values: [
                    {
                      id: 0,
                      label: '1',
                    },
                    {
                      id: 1,
                      label: '2',
                    },
                    {
                      id: 2,
                      label: '3',
                    },
                    {
                      id: 3,
                      label: '4',
                    },
                    {
                      id: 4,
                      label: '5',
                    },
                  ],
                },
              ],
              inputs: [
                {
                  name: 'power_stage1_toh1',
                  label: options.labelPowerElectricStage1,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage2_toh1',
                  label: options.labelPowerElectricStage2,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage3_toh1',
                  label: options.labelPowerElectricStage3,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage4_toh1',
                  label: options.labelPowerElectricStage4,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage5_toh1',
                  label: options.labelPowerElectricStage5,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
              ],
            },
          ],
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      banOnDeletionElement: 'toh2',
      x: coord.toh1_x,
      y: coord.toh1_y,
    },
    // нагреватель 2
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'toh2',
      mark: 'Н2',
      svg: 'toh',
      bottom: 'air7',
      orders: ['count', 'voltage_toh2', 'type_toh2', 'purpose_toh2'],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      references: [
        {
          name: 'voltage_toh2',
          label: options.labelVoltage,
          valueId: 1,
          values: options.valuesVoltage,
          enable: true,
        },
        {
          name: 'type_toh2',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypeHeat,
          referencesValueId: [
            {
              valueId: 0,
              switches: [
                {
                  name: 'thermoalarm_toh2',
                  label: 'Термостат защиты',
                  value: true,
                  enable: true,
                },
                {
                  name: 'pressure_toh2',
                  label: 'Реле перепада давления насоса',
                  value: true,
                  enable: true,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'power_220_toh2',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power220Heater,
                },
                {
                  name: 'power_380_toh2',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power380Heater,
                },
                {
                  name: 'count_stage_toh2',
                  label: 'Количество ступеней',
                  valueId: 0,
                  disable: true,
                  enable: true,
                  values: [
                    {
                      id: 0,
                      label: '1',
                    },
                    {
                      id: 1,
                      label: '2',
                    },
                    {
                      id: 2,
                      label: '3',
                    },
                    {
                      id: 3,
                      label: '4',
                    },
                    {
                      id: 4,
                      label: '5',
                    },
                  ],
                },
              ],
              inputs: [
                {
                  name: 'power_stage1_toh2',
                  label: options.labelPowerElectricStage1,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage2_toh2',
                  label: options.labelPowerElectricStage2,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage3_toh2',
                  label: options.labelPowerElectricStage3,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage4_toh2',
                  label: options.labelPowerElectricStage4,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage5_toh2',
                  label: options.labelPowerElectricStage5,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
              ],
            },
          ],
          enable: true,
        },
        {
          name: 'purpose_toh2',
          label: options.labelHeatPurpose,
          valueId: 0,
          values: options.valuesHeatPurpose,
          enable: true,
        },
      ],
      x: coord.toh2_x,
      y: coord.toh2_y,
    },
    // нагреватель 3
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'toh3',
      mark: 'Н2',
      svg: 'toh',
      bottom: 'air8',
      orders: ['count', 'voltage_toh3', 'type_toh3'],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      references: [
        {
          name: 'voltage_toh3',
          label: options.labelVoltage,
          valueId: 1,
          values: options.valuesVoltage,
          enable: true,
        },
        {
          name: 'type_toh3',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypeHeat,
          referencesValueId: [
            {
              valueId: 0,
              switches: [
                {
                  name: 'thermoalarm_toh3',
                  label: 'Термостат защиты',
                  value: true,
                  enable: true,
                },
                {
                  name: 'pressure_toh3',
                  label: 'Реле перепада давления насоса',
                  value: true,
                  enable: true,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'power_220_toh3',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power220Heater,
                },
                {
                  name: 'power_380_toh3',
                  label: 'Мощность, кВт',
                  valueId: 0,
                  enable: true,
                  disable: false,
                  values: options.power380Heater,
                },
                {
                  name: 'count_stage_toh3',
                  label: 'Количество ступеней',
                  valueId: 0,
                  disable: true,
                  enable: true,
                  values: [
                    {
                      id: 0,
                      label: '1',
                    },
                    {
                      id: 1,
                      label: '2',
                    },
                    {
                      id: 2,
                      label: '3',
                    },
                    {
                      id: 3,
                      label: '4',
                    },
                    {
                      id: 4,
                      label: '5',
                    },
                  ],
                },
              ],
              inputs: [
                {
                  name: 'power_stage1_toh3',
                  label: options.labelPowerElectricStage1,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage2_toh3',
                  label: options.labelPowerElectricStage2,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage3_toh3',
                  label: options.labelPowerElectricStage3,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage4_toh3',
                  label: options.labelPowerElectricStage4,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
                {
                  name: 'power_stage5_toh3',
                  label: options.labelPowerElectricStage5,
                  value: 4.5,
                  type: 'number',
                  rules: options.rulesPowerStages,
                  enable: true,
                  disable: true,
                },
              ],
            },
          ],
          enable: true,
        },
      ],
      x: 14,
      y: par_postrecuperator.y,
    },

    // охладитель 1
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'toc1',
      mark: 'О1',
      svg: 'cooler',
      bottom: 'air9',
      orders: ['count', 'type_toc1'],
      references: [
        {
          name: 'type_toc1',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypeCool,
          referencesValueId: [
            {
              valueId: 0,
              inputs: [
                {
                  name: 'count_countur_toc1',
                  label: options.labelCountCounturCoolFreon,
                  value: 1,
                  type: 'number',
                  enable: true,
                  rules: options.rulesCountCounturCoolFreon,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'voltage_pump_toc1',
                  label: 'Напряжение насоса, В',
                  valueId: 1,
                  values: options.valuesVoltage,
                },
                {
                  name: 'manual_type_toc1',
                  label: 'Тип управления',
                  valueId: 0,
                  values: options.valuesTypeManual,
                },
              ],
              inputs: [
                {
                  name: 'pump_power_toc1',
                  label: 'Мощность насоса, кВт',
                  value: 0.15,
                  type: 'number',
                  enable: true,
                },
              ],
            },
          ],
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      banOnDeletionElement: 'toc2',
      x: coord.toc1_x,
      y: coord.toc1_y,
    },
    // охладитель 2
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'toc2',
      mark: 'О2',
      svg: 'cooler',
      bottom: 'air10',
      orders: ['count', 'type_toc2'],
      references: [
        {
          name: 'type_toc2',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypeCool,
          referencesValueId: [
            {
              valueId: 0,
              inputs: [
                {
                  name: 'count_countur_toc2',
                  label: options.labelCountCounturCoolFreon,
                  value: 1,
                  type: 'number',
                  enable: true,
                  rules: options.rulesCountCounturCoolFreon,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'voltage_pump_toc2',
                  label: 'Напряжение насоса, В',
                  valueId: 1,
                  values: options.valuesVoltage,
                },
                {
                  name: 'manual_type_toc2',
                  label: 'Тип управления',
                  valueId: 0,
                  values: options.valuesTypeManual,
                },
              ],
              inputs: [
                {
                  name: 'pump_power_toc2',
                  label: 'Мощность насоса, кВт',
                  value: 0.75,
                  type: 'number',
                  enable: true,
                },
              ],
            },
          ],
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCount,
        },
      ],
      x: coord.toc2_x,
      y: coord.toc2_y,
    },
    // увлажнитель
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'hum',
      mark: 'У1',
      svg: 'humdity',
      bottom: 'air11',
      orders: ['type_hum'],
      references: [
        {
          name: 'type_hum',
          label: options.labelHumidifier,
          valueId: 0,
          values: options.valuesHumidifierType,
          enable: true,
          referencesValueId: [
            {
              valueId: 0,

            },
            {
              valueId: 1,
              inputs: [
                {
                  name: 'pump_power_hum',
                  label: 'Мощность насоса, кВт',
                  value: 0.75,
                  type: 'number',
                  rules: options.rulesPowerPump,
                  enable: true,
                },
              ],
            },
          ],
        },
      ],
      x: coord.hum_x,
      y: coord.hum_y,
    },
    // резерв
    {
      el: 'air12',
      x: 8,
      y: 2,
    },
    {
      enabled: true,
      manual: false,
      enable: false,
      el: 'fnresinp',
      bottom: 'air13',
      x: coord.fnresinp_x,
      y: coord.fnresinp_y,
      w: 1,
      h: 2,
      bottom_w: 1,
      bottom_h: 1,
    },
    {
      el: 'air14',
      x: coord.vpv1_x,
      y: coord.vpv1_y,
    },
    {
      enabled: false, // вентилятор притока не отключается НИКОГДА
      el: 'pv1',
      svg: 'fan',
      mark: 'ВП1',
      orders: ['count', 'type_pv1', 'voltage_pv1', 'power_pv1', 'current_pv1', 'pressure_pv1', 'thermocontact_pv1', 'speedmanual_pv1', 'reserve_pv1'],
      references: [
        {
          name: 'type_pv1',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypesFans,
          enable: true,
        },
        {
          name: 'voltage_pv1',
          label: options.labelVoltage,
          valueId: 0,
          values: options.valuesVoltage,
          enable: true,
        },
      ],
      switches: [
        {
          name: 'pressure_pv1',
          label: 'Реле перепада давления',
          value: true,
          enable: true,
        },
        {
          name: 'thermocontact_pv1',
          label: 'Наличие термоконтакта',
          value: true,
          enable: true,
        },
        {
          name: 'speedmanual_pv1',
          label: 'Регулировка скорости',
          value: true,
          enable: true,
        },
        {
          name: 'reserve_pv1',
          label: 'Резерв',
          value: false,
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'power_pv1',
          label: options.labelPower,
          value: 1.5,
          type: 'number',
          rules: options.rulesPowerFans,
          enable: true,
        },
        {
          name: 'current_pv1',
          label: 'Ном. ток, А',
          value: 4,
          type: 'number',
          rules: options.rulesCurrent,
          enable: true,
        },
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          rules: options.rulesCount,
          enable: true,
        },
      ],
      x: coord.pv1_x,
      y: coord.pv1_y,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      bottom: 'air16',
      el: 'fnresoutp',
      x: coord.fnresoutp_x,
      y: coord.fnresoutp_y,
      w: 1,
      h: 2,
      bottom_w: 1,
      bottom_h: 1,
    },
    // резерв
    {
      el: 'air17',
      x: 26,
      y: par_postrecuperator.y,
    },
    // резерв
    {
      el: 'air18',
      x: 27,
      y: par_postrecuperator.y,
    },
    // датчик температуры наружней
    {
      enabled: true,
      manual: true,
      enable: false,
      el: 'tnar',
      mark: 'ТН1',
      svg: 'temperature',
      x: 1,
      y: 4,
    },
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'hummes',
      svg: 'humdityMes',
      mark: 'ТВ1',
      bottom: 'air19',
      x: coord.hummes_x,
      y: coord.hummes_y,
    },
    {
      enabled: true,
      enable: false,
      manual: true,
      bottom: 'air20',
      mark: 'ДУ1',
      el: 'co2',
      svg: 'co2',
      x: coord.co2_x,
      y: coord.co2_y,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      bottom: 'air21',
      enableManual: true,
      mark: 'ДС1',
      el: 'spd',
      x: 25,
      y: par_postrecuperator.y,
    },
    {
      enabled: true, // датчик давления в канале притока
      enable: false,
      manual: false,
      el: 'press',
      mark: 'ДД1',
      enableManual: true,
      bottom: 'air22',
      x: coord.press_x,
      y: coord.press_y,
    },
    {
      enabled: true, // датчик температуры в канале притока
      enable: false,
      manual: false,
      el: 'tkan',
      bottom: 'air23',
      mark: 'ТК1',
      svg: 'temperature',
      enableManual: true,
      x: coord.tkan_x,
      y: coord.tkan_y,
    },
    {
      el: 'air24',
      x: 29,
      y: par_postrecuperator.y,
    },
    // датчик температуры в помещении
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'troom',
      mark: 'ТП1',
      svg: 'temperature',
      x: 30,
      y: 3,
    },
    // датчик угарного газа СО
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'co',
      mark: 'ДУг1',
      x: 30,
      y: 4,
    },
    // датчик углекислого газа СО2
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'co2room',
      mark: 'ДУ(п)1',
      svg: 'co2',
      x: 30,
      y: 6,
    },
    // датчик влажности комнатный
    {
      enabled: true,
      enable: false,
      manual: true,
      el: 'hummesroom',
      svg: 'humdityMes',
      mark: 'ТВ(п)1',
      x: 30,
      y: 7,
    },
    // рекуператор
    {
      enabled: true,
      el: 'rec',
      enable: false,
      manual: true,
      bottom: 'noRecInflow',
      orders: ['type_rec'],
      references: [
        {
          name: 'type_rec',
          label: options.labelTypeRecuperator,
          valueId: 0,
          values: options.valuesTypesRecuperator,
          enable: true,
          referencesValueId: [
            {
              valueId: 0,
              references: [
                {
                  name: 'bypass_rec',
                  label: 'Байпас рекуператора',
                  valueId: 0,
                  values: options.valuesTypeManual,
                  enable: true,
                },
              ],
              switches: [
                {
                  name: 'pressure_rec',
                  label: 'Контроль обмерзания по прессостату',
                  value: true,
                  enable: true,
                },
                {
                  name: 'heat_rec',
                  label: 'Греющий кабель на поддон для конденсата',
                  value: false,
                  enable: true,
                },
              ],
            },
            {
              valueId: 1,
              references: [
                {
                  name: 'voltage',
                  label: options.labelVoltage,
                  valueId: 0,
                  values: options.valuesVoltage,
                  enable: true,
                },
              ],
              inputs: [
                {
                  name: 'current',
                  label: 'Номинальный ток привода ротора, А',
                  value: 4,
                  type: 'number',
                  enable: true,
                  rules: options.rulesCurrentRotor,
                },
              ],
            },
          ],
        },
      ],
      enableElements: ['tud'],
      x: 9,
      y: 2,
      w: 3,
      h: 4,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air25',
      x: 28,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air26',
      x: 27,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air27',
      x: 26,
      y: 2,
    },
    // фильтр вытяжки
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'vf1',
      mark: 'ФВ1',
      svg: 'filter',
      // bottom: 'air28',
      orders: ['count'],
      inputs: [
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          enable: true,
          rules: options.rulesCountFilters,
        },
      ],
      x: 25,
      y: 2,
    },
    // взамен фильтра вытяжки 2
    {
      enabled: true,
      enable: false,
      manual: false,
      enableManual: true,
      el: 'air29',
      x: 24,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air30',
      x: 23,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air31',
      x: 22,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air32',
      x: 21,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air33',
      x: 20,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air34',
      x: 19,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air35',
      x: 18,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air36',
      x: 17,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air37',
      x: 16,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air38',
      x: 15,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air39',
      x: 14,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air40',
      x: 13,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air41',
      x: 12,
      y: 2,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air42',
      x: 8,
      y: 5,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air43',
      x: 7,
      y: 5,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air44',
      x: 6,
      y: 5,
    },
    {
      enabled: true,
      enable: false,
      manual: false,
      el: 'air45',
      x: 4,
      y: 5,
    },
    {
      enabled: true, // датчик температуры в вытяжном канале
      enable: false,
      manual: false,
      el: 'tud',
      bottom: '',
      mark: 'ТВ1',
      svg: 'temperature',
      isHideBottom: {
        enable: 'vv1',
        bottom: 'air46',
      },
      enableManual: true,
      x: 3,
      y: 5,
    },

    {
      enabled: true, // вентилятор вытяжки отключаемый
      enable: false,
      manual: true,
      el: 'vv1',
      mark: 'ВВ1',
      svg: 'fan',
      orders: ['count', 'type_vv1', 'voltage_vv1', 'power_vv1', 'current_vv1', 'pressure_vv1', 'thermocontact_vv1', 'speedmanual_vv1', 'reserve_vv1'],
      references: [
        {
          name: 'type_vv1',
          label: options.labelType,
          valueId: 0,
          values: options.valuesTypesFans,
          enable: true,
        },
        {
          name: 'voltage_vv1',
          label: options.labelVoltage,
          valueId: 0,
          values: options.valuesVoltage,
          enable: true,
        },
      ],
      switches: [
        {
          name: 'pressure_vv1',
          label: 'Реле перепада давления',
          value: true,
          enable: true,
        },
        {
          name: 'thermocontact_vv1',
          label: 'Наличие термоконтакта',
          value: true,
          enable: true,
        },
        {
          name: 'speedmanual_vv1',
          label: 'Регулировка скорости',
          value: true,
          enable: true,
        },
        {
          name: 'reserve_vv1',
          label: 'Резерв',
          value: false,
          enable: true,
        },
      ],
      inputs: [
        {
          name: 'current_vv1',
          label: 'Ном. ток, А',
          value: 4,
          type: 'number',
          enable: true,
        },
        {
          name: 'power_vv1',
          label: options.labelPower,
          value: 1.5,
          type: 'number',
          rules: options.rulesPowerFans,
          enable: true,
        },
        {
          name: 'count',
          label: 'Количество, шт',
          value: 1,
          type: 'number',
          rules: options.rulesCount,
          enable: true,
        },
      ],
      enableElements: [
        'arrow3',
        'arrow4',
        'air25',
        'air26',
        'air27',
        'vf1',
        'air29',
        'air30',
        'air31',
        'air32',
        'air33',
        'air34',
        'air35',
        'air36',
        'air37',
        'air38',
        'air39',
        'air40',
        'air41',
        'air42',
        'air43',
        'air44',
        'air45',
        'vvlv1',
        'air48',
      ],
      x: coord.vv1_x,
      y: coord.vv1_y,
    },
  ],
};
const confM245 = [
  {
    id: 'Q1',
    type: ['do'],
  },
  {
    id: 'Q2',
    type: ['do'],
  },
  {
    id: 'Q3',
    type: ['do'],
  },
  {
    id: 'Q4',
    type: ['do'],
  },
  {
    id: 'Q5',
    type: ['do'],
  },
  {
    id: 'Uin1',
    type: ['di'],
  },
  {
    id: 'Uin2',
    type: ['di'],
  },
  {
    id: 'Uin3',
    type: ['di'],
  },
  {
    id: 'Uin4',
    type: ['di'],
  },
  {
    id: 'Uin5',
    type: ['di'],
  },
  {
    id: 'Uin6',
    type: ['di'],
  },
  {
    id: 'Uin7',
    type: ['di'],
  },
  {
    id: 'Uin8',
    type: ['di'],
  },
  {
    id: 'Uin9',
    type: ['di'],
  },
  {
    id: 'Uin10',
    type: ['di'],
  },
  {
    id: 'Uin11',
    type: ['di'],
  },
  {
    id: 'Uin12',
    type: ['di'],
  },
  {
    id: 'Uin13',
    type: ['di/ai'],
  },
  {
    id: 'Uin14',
    type: ['di/ai'],
  },
  {
    id: 'Uin15',
    type: ['di/ai'],
  },
  {
    id: 'Uin16',
    type: ['di/ai'],
  },
  {
    id: 'Uin17',
    type: ['di/ai'],
  },
  {
    id: 'Uin18',
    type: ['di/ai'],
  },
  {
    id: 'U1',
    type: ['do/ai/ao'],
  },
  {
    id: 'U2',
    type: ['do/ai/ao'],
  },
  {
    id: 'U3',
    type: ['do/ai/ao'],
  },
  {
    id: 'U4',
    type: ['do/ai/ao'],
  },
  {
    id: 'U5',
    type: ['do/ai/ao'],
  },
  {
    id: 'U6',
    type: ['do/ai/ao'],
  },
  {
    id: 'U7',
    type: ['do/ao'],
  },
  {
    id: 'U8',
    type: ['do/ao'],
  },
];
const confM100 = [
  {
    id: 'DO1',
    type: ['do'],
  },
  {
    id: 'DO2',
    type: ['do'],
  },
  {
    id: 'DO3',
    type: ['do'],
  },
  {
    id: 'DO4',
    type: ['do'],
  },
  {
    id: 'DO5',
    type: ['do'],
  },
  {
    id: 'Uin1',
    type: ['di'],
  },
  {
    id: 'Uin2',
    type: ['di'],
  },
  {
    id: 'Uin3',
    type: ['di'],
  },
  {
    id: 'Uin4',
    type: ['di'],
  },
  {
    id: 'Uin5',
    type: ['di'],
  },
  {
    id: 'Uin6',
    type: ['di'],
  },
  {
    id: 'Uin7',
    type: ['di'],
  },
  {
    id: 'Uin8',
    type: ['di'],
  },
  {
    id: 'Uin9',
    type: ['di'],
  },
  {
    id: 'AOUT1',
    type: ['ao'],
  },
  {
    id: 'AOUT2',
    type: ['ao'],
  },
];

const algorythm = {
  // 0 -условие if

  // лог операции
  // 0 - равно
  // 1 - не равно

  // мат операции
  // 0 - сумма
  // 1 - вычитание
  procedures: [
    {
      type: 0,
      arguments: [
        {
          operation: 0,
          argument0: '',
          argument1: 1,
        },
        {
          operation: 0,
          argument0: '',
          argument1: 1,
        },
      ],
    },
  ],
};
export {
  defaultStructure, options, confM245, confM100, algorythm,
};
